--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.6
-- Dumped by pg_dump version 9.5.6

-- Started on 2020-01-07 09:14:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

DROP TABLE resource CASCADE; 

--
-- TOC entry 250 (class 1259 OID 26703)
-- Name: resource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE resource (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    code_autogenerated boolean NOT NULL,
    base_calendar_id bigint,
    resource_type character varying(64) NOT NULL
);


ALTER TABLE resource OWNER TO postgres;

--
-- TOC entry 2498 (class 0 OID 26703)
-- Dependencies: 250
-- Data for Name: resource; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2378 (class 2606 OID 26980)
-- Name: resource_base_calendar_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY resource
    ADD CONSTRAINT resource_base_calendar_id_key UNIQUE (base_calendar_id);


--
-- TOC entry 2380 (class 2606 OID 26982)
-- Name: resource_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY resource
    ADD CONSTRAINT resource_code_key UNIQUE (code);


--
-- TOC entry 2382 (class 2606 OID 26707)
-- Name: resource_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY resource
    ADD CONSTRAINT resource_pkey PRIMARY KEY (id);


--
-- TOC entry 2383 (class 2606 OID 27515)
-- Name: fkebabc40edc874c20; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY resource
    ADD CONSTRAINT fkebabc40edc874c20 FOREIGN KEY (base_calendar_id) REFERENCES resource_calendar(base_calendar_id);


-- Completed on 2020-01-07 09:14:39

--
-- PostgreSQL database dump complete
--

