--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.6
-- Dumped by pg_dump version 9.5.6

-- Started on 2020-01-07 09:53:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

DROP TABLE base_calendar CASCADE;

--
-- TOC entry 189 (class 1259 OID 26363)
-- Name: base_calendar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE base_calendar (
    id bigint NOT NULL,
    version bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255),
    code_autogenerated boolean,
    last_sequence_code integer
);


ALTER TABLE base_calendar OWNER TO postgres;

--
-- TOC entry 2495 (class 0 OID 26363)
-- Dependencies: 189
-- Data for Name: base_calendar; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO base_calendar (id, version, code, name, code_autogenerated, last_sequence_code) VALUES (202, 1, 'CALENDAR0001', 'Default', true, 0);


--
-- TOC entry 2378 (class 2606 OID 26922)
-- Name: base_calendar_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY base_calendar
    ADD CONSTRAINT base_calendar_code_key UNIQUE (code);


--
-- TOC entry 2380 (class 2606 OID 26370)
-- Name: base_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY base_calendar
    ADD CONSTRAINT base_calendar_pkey PRIMARY KEY (id);


-- Completed on 2020-01-07 09:53:50

--
-- PostgreSQL database dump complete
--

